version: "3.9"

services:
    db:
      image: postgres:14.5-alpine
      container_name: db
      volumes:
        - ./data/db:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_HOST=${POSTGRES_HOST}

      networks:
        - mynetwork
  
    web:
      build: .
      container_name: web
      volumes:
        - .:/code
      ports:
        - '80:80'
        # - '3500:3500'
      command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py collectstatic --no-input && python3 manage.py runserver 0.0.0.0:80"
      depends_on:
        - db 
      environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_HOST=${POSTGRES_HOST}
        - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
        - DEBUG= ${DEBUG}
        - ADMIN_PAGE_URL={ADMIN_PAGE_URL}
        - SECRET_KEY=${SECRET_KEY}
      networks:
        - mynetwork

networks:
  mynetwork:
    driver: bridge

# collectstatic --no-input && python manage.py makemigrations && python manage.py migrate && python manage.py 
