# Generated by Django 4.1.1 on 2022-09-25 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("primary_contact_first_name", models.CharField(max_length=50)),
                ("primary_contact_last_name", models.CharField(max_length=50)),
                ("primary_contact_email", models.CharField(max_length=50, unique=True)),
                (
                    "primary_contact_phone_number",
                    models.CharField(max_length=50, unique=True),
                ),
                ("primary_contact_phone_type", models.CharField(max_length=50)),
                ("secondary_contact_first_name", models.CharField(max_length=50)),
                ("secondary_contact_last_name", models.CharField(max_length=50)),
                (
                    "secondary_contact_email",
                    models.CharField(max_length=50, unique=True),
                ),
                (
                    "secondary_contact_phone_number",
                    models.CharField(max_length=50, unique=True),
                ),
                ("secondary_contact_phone_type", models.CharField(max_length=50)),
                ("street_address_line_1", models.CharField(max_length=50)),
                ("street_address_line_2", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("zip", models.IntegerField()),
                ("country", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ClientCalenderTokenModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.CharField(max_length=300)),
                ("refresh_token", models.CharField(max_length=300)),
                ("token_uri", models.CharField(max_length=100)),
                ("token_expiry", models.CharField(max_length=50)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
